services:
  web:
    build:
      dockerfile: Dockerfile
      args:
        WEB_UID: ${WEB_UID:-114}
        WEB_GID: ${WEB_GID:-121}
    volumes:
      - .:/app
    environment:
      XDEBUG_ENABLED: true
      XDEBUG_MODE: coverage
      AWS_URL: 'http://localhost:${FORWARD_MINIO_PORT:-9001}'
      AWS_ENDPOINT: 'http://minio:${FORWARD_MINIO_PORT:-9001}'
      MINIO_URL: 'http://localhost:${FORWARD_MINIO_PORT:-9001}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID:-AKIAIOSFODNN7EXAMPLE}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}'
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 30
  job:
    build:
      dockerfile: Dockerfile
      args:
        WEB_UID: ${WEB_UID:-114}
        WEB_GID: ${WEB_GID:-121}
    volumes:
      - .:/app
    environment:
      CONTAINER_ROLE: 'job'
      WEB_UID: '${WEB_UID:-114}'
      WEB_GID: '${WEB_GID:-121}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID:-AKIAIOSFODNN7EXAMPLE}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}'
    depends_on:
      web:
        condition: service_healthy
    networks:
      - app-network
  mysql:
    image: 'mysql:8.0.33'
    hostname: mysql
    environment:
      XDEBUG_ENABLED: '${XDEBUG_ENABLED:-true}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - 'app-mysql:/var/lib/mysql'
      - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - '-p${DB_PASSWORD}'
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    hostname: redis
    volumes:
      - 'app-redis:/data'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
  s3:
    hostname: minio
    image: 'minio/minio:latest'
    environment:
      MINIO_ROOT_USER: '${AWS_ACCESS_KEY_ID:-AKIAIOSFODNN7EXAMPLE}'
      MINIO_ROOT_PASSWORD: '${AWS_SECRET_ACCESS_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}'
      MINIO_DEFAULT_BUCKET: '${AWS_BUCKET:-default_bucket}'
    volumes:
      - 'app-minio:/data/minio'
    networks:
      - app-network
    command: minio server /data/minio --console-address ":${FORWARD_MINIO_CONSOLE_PORT:-8900}" --address ":${FORWARD_MINIO_PORT:-9001}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${FORWARD_MINIO_PORT:-9001}/minio/health/live" ]
      retries: 3
      timeout: 5s
  # Create a service that only creates a default bucket.
  createbuckets:
    image: minio/mc
    depends_on:
      - s3
    networks:
      - app-network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9001 ${AWS_ACCESS_KEY_ID:-AKIAIOSFODNN7EXAMPLE} ${AWS_SECRET_ACCESS_KEY:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY};
      /usr/bin/mc rm -r --force myminio/${AWS_BUCKET:-storage-local};
      /usr/bin/mc mb myminio/${AWS_BUCKET:-storage-local};
      /usr/bin/mc policy set download myminio/${AWS_BUCKET:-storage-local};
      exit 0;
      "
networks:
  app-network:
    driver: bridge
volumes:
  app-mysql:
    driver: local
  app-redis:
    driver: local
  app-minio:
    driver: local
